  steps:
  # Pull the latest container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/frontend || exit 0']
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/frontend', './frontend',
      '--cache-from', 'gcr.io/$PROJECT_ID/frontend'
    ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'frontend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/frontend'
    - '--region'
    - 'us-east4'
  images:
  - 'gcr.io/$PROJECT_ID/frontend'
